# Generated by Django 5.2.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdmissionsFormTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("school_id", models.CharField(db_index=True, max_length=120)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("opens_at", models.DateTimeField()),
                ("closes_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["school_id", "name"],
                "unique_together": {("school_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="ComplianceProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("school_id", models.CharField(max_length=120, unique=True)),
                ("retention_days", models.PositiveIntegerField(default=365)),
                ("requires_parental_consent", models.BooleanField(default=True)),
                ("allows_data_export", models.BooleanField(default=True)),
                ("allows_right_to_delete", models.BooleanField(default=True)),
                ("data_residency_region", models.CharField(default="auto", max_length=80)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["school_id"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionsFormField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(max_length=80),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("email", "Email"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("select", "Select"),
                            ("file", "File"),
                            ("boolean", "Boolean"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("options_json", models.JSONField(blank=True, default=list)),
                ("validation_json", models.JSONField(blank=True, default=dict)),
                (
                    "template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="ops.admissionsformtemplate"),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "unique_together": {("template", "key")},
            },
        ),
    ]
