# Generated by Django 5.2.7 on 2026-01-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_school_customuser_created_by_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admin_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
