# Generated by Django 5.2.7 on 2026-01-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_school_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
