# Generated by Django 5.2.1 on 2026-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_school_is_suspended_school_suspended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('hr', 'HR'), ('accountant', 'Accountant'), ('superadmin', 'Super Admin')], db_index=True, max_length=20),
        ),
    ]
