# Generated by Django 5.2.1 on 2026-03-05 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_db_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SUSPEND', 'Suspend'), ('APPROVE', 'Approve')], db_index=True, max_length=20)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.school')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_academic_year', models.CharField(default='2025', max_length=20)),
                ('current_term', models.CharField(default='Term 1', max_length=50)),
                ('term_start_date', models.DateField(blank=True, null=True)),
                ('term_end_date', models.DateField(blank=True, null=True)),
                ('grading_system', models.CharField(choices=[('zimsec', 'ZIMSEC (A-U)'), ('cambridge', 'Cambridge International'), ('percentage', 'Percentage Only')], default='zimsec', max_length=20)),
                ('school_motto', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('timezone', models.CharField(default='Africa/Harare', max_length=50)),
                ('max_students_per_class', models.IntegerField(default=40)),
                ('late_fee_percentage', models.FloatField(default=0.0, help_text='Percentage charged on overdue fees')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.school')),
            ],
        ),
    ]
