# Generated by Django 5.2.1 on 2026-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auditlog_schoolsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='paynow_integration_id',
            field=models.CharField(blank=True, help_text='PayNow Zimbabwe integration ID for this school', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='paynow_integration_key',
            field=models.CharField(blank=True, help_text='PayNow Zimbabwe integration key for this school', max_length=255),
        ),
    ]
