# Generated by Django 5.2.1 on 2026-03-23 11:54

from django.db import migrations


def fix_empty_phone_numbers(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(phone_number='').update(phone_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_paynow_credentials_to_school_settings'),
    ]

    operations = [
        migrations.RunPython(fix_empty_phone_numbers, migrations.RunPython.noop),
    ]
