# Generated by Django 5.2.1 on 2026-03-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id']},
        ),
    ]
