# Generated by Django 5.2.1 on 2026-03-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_school_to_feetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='term_1_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='term_1_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='term_2_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='term_2_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='term_3_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='term_3_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
