# Generated by Django 5.2.1 on 2026-03-30 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_per_term_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='report_logos/')),
                ('stamp_image', models.ImageField(blank=True, upload_to='report_stamps/')),
                ('primary_color', models.CharField(default='#1d4ed8', max_length=7)),
                ('secondary_color', models.CharField(default='#f3f4f6', max_length=7)),
                ('show_grading_key', models.BooleanField(default=True)),
                ('show_attendance', models.BooleanField(default=True)),
                ('show_overall_average', models.BooleanField(default=True)),
                ('principal_name', models.CharField(blank=True, max_length=120)),
                ('principal_title', models.CharField(blank=True, default='Head of School', max_length=120)),
                ('show_class_teacher', models.BooleanField(default=True)),
                ('teacher_comments_default', models.TextField(blank=True, help_text='Default teacher comment on every report')),
                ('principal_comments_default', models.TextField(blank=True, help_text='Default principal comment on every report')),
                ('show_next_term_dates', models.BooleanField(default=True, help_text='Show next term opening/closing (hidden for Term 3)')),
                ('custom_footer_text', models.CharField(blank=True, max_length=255)),
                ('show_grade_remark', models.BooleanField(default=True, help_text='Show Distinction/Merit/Credit etc.')),
                ('show_exam_types', models.BooleanField(default=True, help_text='Show individual exam types vs aggregated average')),
                ('highlight_pass_fail', models.BooleanField(default=False, help_text='Color-code rows by grade')),
                ('watermark_text', models.CharField(blank=True, max_length=60)),
                ('border_style', models.CharField(choices=[('simple', 'Simple Line'), ('decorative', 'Decorative'), ('none', 'No Border')], default='simple', max_length=15)),
                ('show_conduct_section', models.BooleanField(default=False)),
                ('show_activities_section', models.BooleanField(default=False)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_config', to='users.school')),
            ],
        ),
    ]
