# Generated by Django 5.2.1 on 2026-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_report_card_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardconfig',
            name='logo_position',
            field=models.CharField(choices=[('left', 'Left of School Name'), ('right', 'Right of School Name'), ('center', 'Centered Above Name')], default='center', max_length=10),
        ),
    ]
