# Generated by Django 6.0.4 on 2026-04-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_reportcard_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcardconfig',
            name='comment_char_limit',
            field=models.IntegerField(default=250, help_text='Max chars for per-subject teacher comments'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='one_page_fit',
            field=models.BooleanField(default=False, help_text='Auto-shrink to one page'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='show_attendance_breakdown',
            field=models.BooleanField(default=False, help_text='Present/absent/late breakdown'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='show_class_average',
            field=models.BooleanField(default=False, help_text='Class average & highest columns'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='show_effort_grade',
            field=models.BooleanField(default=False, help_text='Effort/attitude grade per subject'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='show_fees_status',
            field=models.BooleanField(default=False, help_text='Show fees balance line'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='show_position',
            field=models.BooleanField(default=True, help_text='Position in class'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='show_previous_term',
            field=models.BooleanField(default=False, help_text='Previous-term trend column'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='show_qr_code',
            field=models.BooleanField(default=False, help_text='QR code linking to online verification'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='show_subject_chart',
            field=models.BooleanField(default=False, help_text='Bar chart of subject scores'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='subject_grouping_enabled',
            field=models.BooleanField(default=False, help_text='Group by Core/Electives/Languages'),
        ),
        migrations.AlterField(
            model_name='reportcardconfig',
            name='template_preset',
            field=models.CharField(blank=True, help_text='Last applied preset name', max_length=30),
        ),
        migrations.AlterField(
            model_name='reportcardtemplate',
            name='config_json',
            field=models.JSONField(default=dict, help_text='Snapshot of ReportCardConfig field values'),
        ),
        migrations.AlterField(
            model_name='reportcardtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reportcardtemplate',
            name='is_builtin',
            field=models.BooleanField(default=False, help_text='System-provided presets cannot be deleted'),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
