# Generated by Django 6.0.4 on 2026-04-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_hr_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hrpagepermission',
            new_name='users_hrpag_page_ke_22f237_idx',
            old_name='users_hrpag_page_ke_11a534_idx',
        ),
        migrations.RenameIndex(
            model_name='hrpagepermission',
            new_name='users_hrpag_profile_07919d_idx',
            old_name='users_hrpag_profile_330a26_idx',
        ),
        migrations.RenameIndex(
            model_name='hrpermissionprofile',
            new_name='users_hrper_school__b5f68b_idx',
            old_name='users_hrper_school_5cad95_idx',
        ),
    ]
