# Generated by Django 6.0.4 on 2026-04-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_accountant_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountantpagepermission',
            new_name='users_accou_page_ke_db8c84_idx',
            old_name='users_acctpg_page_key_idx',
        ),
        migrations.RenameIndex(
            model_name='accountantpagepermission',
            new_name='users_accou_profile_b2e9fe_idx',
            old_name='users_acctpg_profile_pk_idx',
        ),
        migrations.RenameIndex(
            model_name='accountantpermissionprofile',
            new_name='users_accou_school__46f56b_idx',
            old_name='users_acctp_school_is_hd_idx',
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Custom logo for the dashboard', null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='primary_color',
            field=models.CharField(default='#2563eb', help_text='Primary accent color for the dashboard', max_length=7),
        ),
        migrations.AlterField(
            model_name='hrpermissionprofile',
            name='is_root_boss',
            field=models.BooleanField(default=False, help_text='Root HR Head has full admin-equivalent access.'),
        ),
    ]
