# Generated by Django 6.0.4 on 2026-04-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_reportcard_default_teacher_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='font_family',
            field=models.CharField(choices=[('sans', 'Sans-Serif (Modern)'), ('serif', 'Serif (Classic)'), ('mono', 'Monospace (Technical)')], default='sans', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='secondary_color',
            field=models.CharField(default='#e0e7ff', help_text='Secondary/background accent color', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='welcome_message',
            field=models.TextField(blank=True, help_text='Custom greeting shown on the dashboard'),
        ),
    ]
