# Generated by Django 6.0.4 on 2026-04-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_schoolsettings_font_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('hr', 'HR'), ('accountant', 'Accountant'), ('security', 'Security'), ('cleaner', 'Cleaner'), ('librarian', 'Librarian'), ('sports_director', 'Sports Director'), ('superadmin', 'Super Admin')], db_index=True, max_length=20),
        ),
    ]
