# Generated by Django 6.0.4 on 2026-04-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuthConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=False, help_text="Is 2FA currently enabled for this user")),
                ("secret_key", models.CharField(blank=True, help_text="Base32-encoded TOTP secret (encrypted)", max_length=255)),
                (
                    "backup_codes",
                    models.JSONField(
                        default=list,
                        help_text='List of hashed backup codes (each code format: {"code_hash": "...", "used": false})',
                    ),
                ),
                ("backup_codes_used", models.JSONField(default=list, help_text="Indices of used backup codes")),
                ("last_ip_address", models.GenericIPAddressField(blank=True, help_text="Last IP address used with 2FA", null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, help_text="Last time user verified with 2FA", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Two Factor Authentication Config",
                "verbose_name_plural": "Two Factor Authentication Configs",
            },
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, help_text="Parsed User-Agent string", max_length=500)),
                ("device_name", models.CharField(blank=True, help_text='User-friendly device name (e.g., "Chrome on Windows")', max_length=255)),
                ("verified", models.BooleanField(default=False, help_text="Requires email confirmation before trusting")),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trusted Device",
                "verbose_name_plural": "Trusted Devices",
                "unique_together": {("user", "ip_address")},
            },
        ),
        migrations.CreateModel(
            name="TwoFactorBackupCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_index", models.IntegerField(help_text="Index of backup code in TwoFactorAuthConfig.backup_codes list")),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                ("used_ip_address", models.GenericIPAddressField()),
                ("used_device", models.CharField(blank=True, help_text="Device info from User-Agent", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_code_audit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Two Factor Backup Code Use",
                "verbose_name_plural": "Two Factor Backup Code Uses",
            },
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="enforce_2fa",
            field=models.BooleanField(default=False, help_text="Enable 2FA enforcement for this school"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="enforce_2fa_for_roles",
            field=models.JSONField(
                default=list,
                help_text='List of roles that must have 2FA enabled (e.g., ["admin", "hr", "accountant"])',
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="enforce_2fa_grace_period_days",
            field=models.IntegerField(default=14, help_text="Days users have to set up 2FA before enforcement"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="enforce_2fa_started_at",
            field=models.DateTimeField(blank=True, help_text="When 2FA enforcement was activated", null=True),
        ),
    ]
