# Generated by Django 6.0.4 on 2026-04-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_two_factor_and_schoolsettings_enforcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='hidden_pages',
            field=models.JSONField(blank=True, default=list, help_text='List of page registry keys (e.g. ["admin.library", "parent.conferences"]) hidden school-wide'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='parent_login_block_message',
            field=models.TextField(blank=True, default='', help_text='Required message shown to parents when login is blocked'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='parent_login_blocked',
            field=models.BooleanField(default=False, help_text='Block all parent logins for this school'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='parent_login_blocked_until',
            field=models.DateTimeField(blank=True, help_text='Informational date shown to parents for when they can log in again', null=True),
        ),
    ]
