# Generated by Django 6.0.4 on 2026-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_customuser_login_lockout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='attendance_period_tracking_start_date',
            field=models.DateField(blank=True, help_text='Date from which period-level bunk detection rules apply.', null=True),
        ),
    ]
