# Generated by Django 6.0.4 on 2026-04-28 13:21

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_schoolsettings_attendance_period_tracking_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='late_assignment_penalty_mode',
            field=models.CharField(choices=[('none', 'No automatic penalty (teacher decides)'), ('flat', 'Flat percentage off late submissions'), ('per_day', 'Percentage off per day late')], default='none', help_text='How late assignment submissions are penalised when allow_late is on', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='late_assignment_penalty_percent',
            field=models.FloatField(default=0.0, help_text='Penalty percentage applied to late submissions (0–100). Used with mode flat or per_day.'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='current_academic_year',
            field=models.CharField(default=users.models.current_year, max_length=20),
        ),
    ]
