# Generated by Django 6.0.4 on 2026-04-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_expand_positions_and_security_cleaning_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-year', '-id']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['employee_id']},
        ),
    ]
