# Generated by Django 6.0.4 on 2026-04-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_payrollpaymentrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payrollpaymentrequest',
            new_name='staff_payro_school__a34457_idx',
            old_name='staff_payro_school__f6f611_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollpaymentrequest',
            new_name='staff_payro_school__7363e2_idx',
            old_name='staff_payro_school__d9fbfd_idx',
        ),
    ]
