# Generated by Django 5.2.7 on 2026-01-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_schoolfees'),
        ('users', '0005_school_admin_password'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolfees',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schoolfees',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_fees', to='users.school'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolfees',
            unique_together={('school', 'grade_level', 'academic_year', 'academic_term')},
        ),
    ]
