# Generated by Django 5.2.7 on 2026-01-30 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_class_break_end_class_break_start_and_more'),
        ('finances', '0004_alter_schoolfees_unique_together_schoolfees_school_and_more'),
        ('users', '0006_school_is_suspended_school_suspended_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.school'),
        ),
        migrations.CreateModel(
            name='StudentPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('school_fees', 'School Fees'), ('other', 'Other Payment')], default='school_fees', max_length=20)),
                ('payment_plan', models.CharField(choices=[('full_year', 'Full Year Payment'), ('two_terms', 'Two Terms Payment'), ('one_term', 'One Term Payment'), ('batch', 'Batch Payment')], default='one_term', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.CharField(max_length=20)),
                ('academic_term', models.CharField(blank=True, max_length=20)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('ecocash', 'EcoCash'), ('innbucks', 'InnBucks'), ('other', 'Other')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('next_payment_due', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='users.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='academics.student')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('ecocash', 'EcoCash'), ('innbucks', 'InnBucks'), ('other', 'Other')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.studentpaymentrecord')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finances.studentpaymentrecord'),
        ),
    ]
