# Generated by Django 5.2.1 on 2026-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_additionalfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='academic_term',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='academic_year',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='studentpaymentrecord',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], db_index=True, default='unpaid', max_length=20),
        ),
    ]
