# Generated by Django 5.2.1 on 2026-03-27 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_add_db_indexes'),
        ('users', '0012_add_school_to_feetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='users.school'),
        ),
    ]
