# Generated by Django 5.2.1 on 2026-04-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_teacher_teaching_classes'),
        ('finances', '0008_add_school_to_feetype'),
        ('users', '0019_school_accommodation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfees',
            name='boarding_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolfees',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TransportFeePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_transport_fee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fee_preferences', to='academics.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fee_preferences', to='academics.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
