# Generated by Django 6.0.4 on 2026-04-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_schoolexpense'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentintent',
            new_name='finances_pa_school__c8363f_idx',
            old_name='finances_pa_school__829a7a_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentintent',
            new_name='finances_pa_school__0d090e_idx',
            old_name='finances_pa_school__0e8ea0_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolexpense',
            new_name='finances_sc_school__374b25_idx',
            old_name='finances_sc_school__3ef12d_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolexpense',
            new_name='finances_sc_school__53bac6_idx',
            old_name='finances_sc_school__d82a0f_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolexpense',
            new_name='finances_sc_school__86f92e_idx',
            old_name='finances_sc_school__1a9628_idx',
        ),
    ]
