# Generated by Django 6.0.4 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_rename_finances_pa_school__829a7a_idx_finances_pa_school__c8363f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentrecord',
            name='covered_terms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentpaymentrecord',
            name='payment_plan',
            field=models.CharField(
                choices=[
                    ('full_year', 'Full Year Payment'),
                    ('two_terms', 'Two Terms Payment'),
                    ('one_term', 'One Term Payment'),
                    ('specific_terms', 'Specific Terms Payment'),
                    ('batch', 'Batch Payment'),
                ],
                default='one_term',
                max_length=20,
            ),
        ),
    ]
