# Generated by Django 5.2.7 on 2026-01-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_class_school_subject_school_alter_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='break_end',
            field=models.TimeField(blank=True, help_text='Morning break end time', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='break_start',
            field=models.TimeField(blank=True, help_text='Morning break start time', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='first_period_start',
            field=models.TimeField(blank=True, help_text='Time first period starts (24hr format, e.g., 07:30)', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='friday_last_period_end',
            field=models.TimeField(blank=True, help_text='Time last period ends on Friday (schools often close early)', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='include_transition_time',
            field=models.BooleanField(default=False, help_text='Include 5 minutes between periods for class changes'),
        ),
        migrations.AddField(
            model_name='class',
            name='last_period_end',
            field=models.TimeField(blank=True, help_text='Time last period ends (24hr format, e.g., 16:00)', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='lunch_end',
            field=models.TimeField(blank=True, help_text='Lunch break end time', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='lunch_start',
            field=models.TimeField(blank=True, help_text='Lunch break start time', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='period_duration_minutes',
            field=models.IntegerField(default=45, help_text='Duration of each period in minutes'),
        ),
    ]
