# Generated by Django 5.2.7 on 2026-02-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_class_break_end_class_break_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
