# Generated by Django 5.2.1 on 2026-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_student_date_of_birth_student_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='academic_term',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='result',
            name='academic_year',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'academic_year', 'academic_term'], name='academics_r_student_e07975_idx'),
        ),
    ]
