# Generated by Django 5.2.1 on 2026-03-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_promotionrecord_activity_activityenrollment_activityevent_accolade_studentaccolade_conferenceslot_conferencebooking_disciplinaryrecord_healthrecord_clinicvisit'),
        ('users', '0012_add_school_to_feetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='parent',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='parents', to='users.school'),
        ),
    ]
