# Generated by Django 5.2.1 on 2026-03-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_add_schools_to_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Priority subjects (e.g. Math, English) get daily periods'),
        ),
    ]
