# Generated by Django 5.2.1 on 2026-03-31 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_result_include_in_report_and_report_term'),
        ('users', '0015_add_logo_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_class',
            field=models.ForeignKey(blank=True, help_text='If set, only users in this class see the announcement', null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.class'),
        ),
        migrations.CreateModel(
            name='ReportCardRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('academic_term', models.CharField(max_length=50)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_releases', to='academics.class')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_releases', to='users.school')),
            ],
            options={
                'unique_together': {('school', 'class_obj', 'academic_year', 'academic_term')},
            },
        ),
    ]
