# Generated by Django 6.0.4 on 2026-04-17 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_announcement_target_audiences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttermfeedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AtRiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(choices=[('grade_drop', 'Grade Drop'), ('prediction_fail', 'Predicted Failure'), ('current_failing', 'Currently Failing'), ('consecutive_d_or_e', 'Consecutive D/E Grades')], max_length=20)),
                ('previous_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('current_grade', models.CharField(max_length=2)),
                ('predicted_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('predicted_percentage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('intervention_scheduled', 'Intervention Scheduled'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='new', max_length=25)),
                ('trend', models.CharField(blank=True, choices=[('up', 'Improving'), ('down', 'Declining'), ('stable', 'Stable')], max_length=20, null=True)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True)),
                ('notified_teacher', models.BooleanField(default=False)),
                ('notified_parent', models.BooleanField(default=False)),
                ('notified_admin', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('intervention_plan', models.TextField(blank=True, help_text='Recommended intervention actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('noted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='at_risk_notes', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_risk_alerts', to='academics.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='at_risk_alerts', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='academics_a_student_c347ab_idx'), models.Index(fields=['school', 'status'], name='academics_a_school__2f5efc_idx'), models.Index(fields=['subject', 'status'], name='academics_a_subject_ba5909_idx')],
            },
        ),
    ]
