# Generated by Django 6.0.4 on 2026-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_result_component_index_result_component_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentplan',
            name='assignments_weight',
            field=models.FloatField(default=0.15, help_text='Weight of combined assignments in final mark (0..1)'),
        ),
        migrations.AddField(
            model_name='assessmentplan',
            name='papers_weight',
            field=models.FloatField(default=0.6, help_text='Weight of combined exam papers in final mark (0..1)'),
        ),
        migrations.AddField(
            model_name='assessmentplan',
            name='tests_weight',
            field=models.FloatField(default=0.25, help_text='Weight of combined tests in final mark (0..1)'),
        ),
    ]
