# Generated by Django 6.0.4 on 2026-04-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_reportcardapprovalrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportcardapprovalrequest',
            new_name='academics_r_school__84b184_idx',
            old_name='academics_r_school__f2bfdb_idx',
        ),
        migrations.RenameIndex(
            model_name='reportcardapprovalrequest',
            new_name='academics_r_school__3b0869_idx',
            old_name='academics_r_school__2bec84_idx',
        ),
        migrations.AddField(
            model_name='activity',
            name='age_group',
            field=models.CharField(choices=[('u13', 'Under 13'), ('u14', 'Under 14'), ('u15', 'Under 15'), ('u16', 'Under 16'), ('u17', 'Under 17'), ('u18', 'Under 18'), ('u19', 'Under 19'), ('u20', 'Under 20'), ('first_team', 'First Team'), ('open', 'Open')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='gender_category',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='level',
            field=models.CharField(choices=[('inter_house', 'Inter-House'), ('inter_school', 'Inter-School'), ('social', 'Social/Recreational')], default='social', max_length=20),
        ),
        migrations.AddField(
            model_name='activityenrollment',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityenrollment',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='match_result',
            field=models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='opponent_score',
            field=models.CharField(blank=True, help_text='e.g. 1, 10, 110/10', max_length=50),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='our_score',
            field=models.CharField(blank=True, help_text='e.g. 2, 14, 120/4', max_length=50),
        ),
    ]
