# Generated by Django 6.0.4 on 2026-04-20 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_assessmentplan_grade_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePointEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchSquadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('played', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameIndex(
            model_name='announcementdismissal',
            new_name='academics_a_user_id_94b6ef_idx',
            old_name='academics_a_user_id_2de620_idx',
        ),
        migrations.AddField(
            model_name='activity',
            name='assistant_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_coached_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityenrollment',
            name='injury_cleared_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityenrollment',
            name='injury_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activityenrollment',
            name='is_injured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='is_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='opponent_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='transport_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('training', 'Training'), ('match', 'Match'), ('tournament', 'Tournament'), ('inter_house', 'Inter-House')], default='training', max_length=20),
        ),
        migrations.AddField(
            model_name='housepointentry',
            name='activity_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.activityevent'),
        ),
        migrations.AddField(
            model_name='housepointentry',
            name='awarded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='housepointentry',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='academics.sportshouse'),
        ),
        migrations.AddField(
            model_name='matchsquadentry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='academics.activityevent'),
        ),
        migrations.AddField(
            model_name='matchsquadentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.activityevent'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student'),
        ),
    ]
