# Generated by Django 6.0.4 on 2026-04-28 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0037_bulkimportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('period_number', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('period_label', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='bulkimportjob',
            new_name='academics_b_school__04fab5_idx',
            old_name='academics_b_school_e96b85_idx',
        ),
        migrations.RenameIndex(
            model_name='bulkimportjob',
            new_name='academics_b_school__93bd70_idx',
            old_name='academics_b_school_3dbbd9_idx',
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='bunk_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='bunk_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='marked_with_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='period_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='period_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancepermission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancepermission',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_permissions', to='academics.class'),
        ),
        migrations.AddField(
            model_name='attendancepermission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancepermission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_permissions', to='academics.student'),
        ),
        migrations.AddIndex(
            model_name='attendancepermission',
            index=models.Index(fields=['student', 'date', 'approved'], name='academics_a_student_df9181_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepermission',
            index=models.Index(fields=['class_assigned', 'date'], name='academics_a_class_a_ac5c1d_idx'),
        ),
    ]
