# Generated by Django 6.0.4 on 2026-04-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0038_attendancepermission_and_more'),
        ('users', '0034_schoolsettings_late_assignment_penalty_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_kind', models.CharField(choices=[('grade', 'Grade'), ('form', 'Form')], db_index=True, max_length=10)),
                ('level_number', models.PositiveSmallIntegerField(db_index=True, help_text='Grade 1-7 or Form 1-6')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('exam_session', models.CharField(blank=True, help_text="e.g. 'June', 'November', 'Mock'", max_length=50)),
                ('paper_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file_key', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('parse_error', models.TextField(blank=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='users.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='academics.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_past_papers', to='academics.teacher')),
            ],
            options={
                'ordering': ['-year', '-date_uploaded'],
                'indexes': [models.Index(fields=['school', 'subject', 'level_kind', 'level_number'], name='academics_p_school__fc358b_idx'), models.Index(fields=['school', 'year'], name='academics_p_school__e33a2f_idx')],
            },
        ),
    ]
