# Generated by Django 6.0.4 on 2026-04-28 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0039_pastexampaper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardDeliveryExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('academic_term', models.CharField(max_length=50)),
                ('reason', models.CharField(choices=[('data_issue', 'Data Issue')], default='data_issue', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_delivery_exclusions', to='academics.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_delivery_exclusions_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_delivery_exclusions', to='users.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_delivery_exclusions', to='academics.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'class_obj', 'academic_year', 'academic_term'], name='academics_r_school__18f5df_idx')],
                'unique_together': {('school', 'class_obj', 'student', 'academic_year', 'academic_term')},
            },
        ),
    ]
