# Generated by Django 6.0.4 on 2026-04-28 16:20

import django.db.models.deletion
from django.db import migrations, models


def backfill_assignment_school(apps, schema_editor):
    Assignment = apps.get_model('academics', 'Assignment')
    for assignment in Assignment.objects.select_related('subject__school').all():
        if assignment.school_id is None and assignment.subject_id and assignment.subject.school_id:
            assignment.school_id = assignment.subject.school_id
            assignment.save(update_fields=['school'])


def reverse_backfill_assignment_school(apps, schema_editor):
    Assignment = apps.get_model('academics', 'Assignment')
    Assignment.objects.update(school_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0040_reportcarddeliveryexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.school'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='academics.assignment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='academics.assignmentsubmission')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.RunPython(backfill_assignment_school, reverse_backfill_assignment_school),
    ]
