# Generated by Django 6.0.4 on 2026-04-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0041_assignment_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_kind', models.CharField(choices=[('grade', 'Grade'), ('form', 'Form')], db_index=True, max_length=10)),
                ('level_number', models.PositiveSmallIntegerField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('total_marks', models.FloatField(default=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('counts_for_report', models.BooleanField(default=False)),
                ('component_index', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule_mode', models.CharField(choices=[('anytime', 'Anytime'), ('scheduled', 'Scheduled')], default='anytime', max_length=20)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('academic_term', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tests', to='academics.assessmentplan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tests', to='academics.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_tests', to='users.school')),
                ('source_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tests', to='academics.pastexampaper')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_tests', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='academics_g_school__7945ef_idx'), models.Index(fields=['school', 'academic_year', 'academic_term'], name='academics_g_school__5f4810_idx'), models.Index(fields=['subject', 'level_kind', 'level_number'], name='academics_g_subject_1da90b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('prompt_text', models.TextField()),
                ('marks', models.FloatField(default=1)),
                ('question_type', models.CharField(choices=[('short', 'Short'), ('long', 'Long'), ('mcq', 'MCQ')], default='short', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, max_length=255)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.generatedtest')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('test', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_score', models.FloatField(default=0)),
                ('manual_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('finalized', 'Finalized')], db_index=True, default='in_progress', max_length=20)),
                ('pushed_to_results', models.BooleanField(db_index=True, default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='academics.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academics.generatedtest')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('test', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('awarded_marks', models.FloatField(default=0)),
                ('teacher_comment', models.TextField(blank=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academics.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academics.testquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
